name: Android Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Linter
        run: ./gradlew ktlintCheck
      - name: Run Test
        run: ./gradlew testDebugUnitTest
      - name: Restore Cache
        uses: actions/cache@v1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build Project
        run: ./gradlew assembleDebug